api_platform:
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
        xml:
            mime_types: ['application/xml', 'text/xml']
        csv:
            mime_types: ['application/csv', 'text/csv']
        yaml:
            mime_types: ['application/yaml', 'text/yaml']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
