name: authentication
recipe: lemp
config:
    webroot: public
    xdebug: true

proxy:
    pma:
        - pma.lemp.lndo.site
        - mariadb.lndo.site

services:
    appserver:
        type: "php"
        version: "7.2"
        config:
            server: nginx.conf

    database:
        type: mariadb:10.3
        creds:
            user: lemp
            password: lemp
            database: authentication

    database_test:
        type: mariadb:10.3
        creds:
            user: lemp
            password: lemp
            database: authentication_test

    pma:
        type: phpmyadmin
        hosts:
            - database
            - database_test

tooling:
    sf:
        service: appserver
        description: "Run Symfony commands: lando sf [command]"
        cmd:
            - bin/console
    phpunit:
        service: appserver
        description: "Run PHP Unit tests: lando phpunit [options]"
        cmd:
            - bin/phpunit --colors=always --coverage-html=build/phpunit/coverage
    behat:
        service: appserver
        description: "Run Behat tests: lando behat [options]"
        cmd:
            - vendor/bin/behat
    phplint:
        service: appserver
        description: "Run PHP lint: lando phplint [options]"
        cmd:
            - vendor/bin/phplint -vvv --no-cache --configuration=./.phplint.yml
    phpmetrics:
        service: appserver
        description: "Run PHP metrics: lando phpmetrics [options]"
        cmd:
            - vendor/bin/phpmetrics --report-html=build/phpmetrics src/
events:
    post-start:
        - appserver: "bin/console doctrine:migration:migrate --no-interaction"
        - appserver: "bin/console doctrine:schema:validate"

        - appserver: "bin/console app::auth:register"
        - appserver: "bin/console app::auth:token"

        - appserver: "bin/console doctrine:migration:migrate --no-interaction --env=test"
        - appserver: "bin/console doctrine:schema:validate --env=test"
